### ISSUE TITLE
Proposal for New Standard: Software & Content License

### ISSUE THREAD

**Issue by simplybenuk** [nhsengland/it-standards#2]
## Proposed name/title
Software & Content Licensing

## Purpose and description
To recommend a standard way in which NHS software code and content should be licensed. This will also help during procurement phases. Existing software that does not conform to these standards could be identified as exceptions.  The [GDS way](Licence) use the following which I feel would be sensible to replicate:

> Unless stated otherwise, the codebase is released under the [MIT License](https://github.com/alphagov/gds-way/blob/master/LICENCE). This covers both the codebase and any sample code in the documentation.
>
>The documentation is [© Crown copyright](http://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/) and available under the terms of the [Open Government 3.0](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/) licence.

## Information domain this standard would relate to

Not sure, this is quite over reaching.

## Existing related standards?

None listed in the standards catalogue, but does relate to the git repo license

## References to related external standards

This is proposed based on the existing [GDS-Way licensing](https://github.com/alphagov/gds-way/blob/master/README.md)

**Comment by TotallyInformation** [comment]
Hi Ben, thanks for this.

You are suggesting MIT rather than Open Gov License v2.0? I thought that was the recommendation for most things published by UK gov and related orgs?

**Comment by simplybenuk** [comment]
Hi Julian,

Not replacing but sitting alongside. 

When I was doing some digging about what to license FutureNHS under I can across [Licensing - The GDS Way](https://gds-way.cloudapps.digital/manuals/licensing.html) which said to use MIT for code and OGL for documentation/content.

My proposal for FutureNHS is that the code base will be shared via MIT, but all content added to the platform will be by default published as Official classification and under the OGL license by default. 

The OGL license for this repo without MIT makes sense as it's not code, so I'm not suggesting replacing that, but adding a general new standard for applications to adhere would be useful.

**Comment by TotallyInformation** [comment]
Nice! OK, I am going to circulate this to other colleagues but this is absolutely the kind of thing we are looking for. 

Are you able to contribute some initial text into the repo? We certainly need a statement on license standards anyway.

**Comment by TotallyInformation** [comment]
I will check the PR shortly but happy to have this in stage 3 now. I don't think there will be any issue with getting to stage 4.
